In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
import numpy as np

Mounted at /content/drive

**1.Прочитайте файл fines.csv, который вы сохранили в предыдущем упражнении.**

In [2]:
fines = pd.read_csv('/content/drive/MyDrive/Школа 21/DS_project10-0/Task 5: обогащение и трансформации/fines.csv')
fines

        CarNumber  Refund   Fines    Make   Model  Year
0    Y163O8161RUS       2  3200.0    Ford   Focus  1997
1     E432XX77RUS       1  6500.0  Toyota   Camry  2004
2     7184TT36RUS       1  2100.0    Ford   Focus  1991
3    X582HE161RUS       2  2000.0    Ford   Focus  1992
4    92918M178RUS       1  5700.0    Ford   Focus  2005
..            ...     ...     ...     ...     ...   ...
925     A001BC154       1    10.0   Honda     FIT  2009
926     A002BC154       2    50.0   Kamaz     200  2015
927     A003BC154       1   200.0    MINI  Cooper  2000
928     A004BC154       2   500.0  Toyota    Vitz  2010
929     A005BC154       1  1000.0    Iran  Khodro  2020

[930 rows x 6 columns]

**2. Итерирование:** во всех следующих подзадачах необходимо рассчитать значение для каждой строки по формуле fines/refund*year, создать новый столбец с полученными данными и измерить время расчета, используя волшебную команду %%timeit в ячейке.

Цикл: напишите функцию, которая выполнит перебор по датафрейму, используя for i in range(0, len(df)), iloc и append() в отношении списка, присвойте результат выполнения функции новому столбцу в датафрейме.

In [3]:
%%timeit
calc = []
for i in range (0, len(fines)):
  calc.append(fines.iloc[i].Fines/fines.iloc[i].Refund*fines.iloc[i].Year)

272 ms ± 7.36 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Сделайте это с помощью функции iterrows().

In [4]:
%%timeit
calc = []
for index, row in fines.iterrows():
  calc.append(row.Fines/row.Refund*row.Year)

46.2 ms ± 795 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

Сделайте это с помощью функции apply() и лямбда-функции.

In [5]:
%%timeit
calc = fines.apply(lambda x: (x.Fines / x.Refund * x.Year), axis=1)

18.3 ms ± 386 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

Сделайте это с помощью объектов Series из датафрейма.

In [6]:
%%timeit
calc = fines.Fines/fines.Refund*fines.Year

205 µs ± 18.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

Сделайте это так же, как и в предыдущей подзадаче, но с помощью метода .values.

In [7]:
%%timeit
calc = fines.Fines.values/fines.Refund.values*fines.Year.values

19 µs ± 2.22 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

**3. Индексация: измерьте опять же время с помощью волшебной команды %%timeit в ячейке.**

Получите значения строки датафрейма для определенного номера CarNumber, например O136HO197RUS.

In [8]:
%%timeit
fines.query('CarNumber == "O136HO197RUS"')

1.17 ms ± 44.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

Установите в качестве индекса в вашем датафрейме CarNumber. Снова попробуйте получить значения строки для того же номера CarNumber.

In [9]:
%%timeit
fines.set_index('CarNumber').loc['O136HO197RUS']

632 µs ± 9.84 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

**4. Даункастинг (работа с типами данных):**

Выполните команду df.info(memory_usage='deep'), обратите внимание на Dtype и объем используемой оперативной памяти;

In [10]:
fines.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  930 non-null    object
 1   Refund     930 non-null    int64
 2   Fines      930 non-null    float64
 3   Make       930 non-null    object
 4   Model      919 non-null    object
 5   Year       930 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 196.5 KB

копируйте с помощью команды copy() исходный датафрейм в другой под названием optimized;

In [11]:
optimized = fines.copy()

Выполните приведение типа вниз с float64 по float32 для всех столбцов;
Выполните приведение вниз с int64 до наименьшего возможного числового dtype;

In [12]:
optimized=optimized.astype({'Fines':'float32', 'Refund':'int8', 'Year':'int8'})

Запустите info(memory_usage='deep') теперь для нового датафрейма, обратите внимание на Dtype и объем используемой оперативной памяти.

In [13]:
optimized.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  930 non-null    object
 1   Refund     930 non-null    int8
 2   Fines      930 non-null    float32
 3   Make       930 non-null    object
 4   Model      919 non-null    object
 5   Year       930 non-null    int8
dtypes: float32(1), int8(2), object(3)
memory usage: 180.2 KB

**5.Категории:**

Измените столбцы типа object на тип category;

In [14]:
optimized=optimized.astype({'CarNumber':'category', 'Make':'category', 'Model':'category'})

В этот раз проверьте объем используемой оперативной памяти; вероятно, он уменьшился в 2-3 раза по сравнению с тем, что использовался исходным датафреймом.

In [15]:
optimized.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  930 non-null    category
 1   Refund     930 non-null    int8
 2   Fines      930 non-null    float32
 3   Make       930 non-null    category
 4   Model      919 non-null    category
 5   Year       930 non-null    int8
dtypes: category(3), float32(1), int8(2)
memory usage: 63.7 KB

**6.Очистка памяти:**

С помощью %reset_selective и библиотеки gc очистите память только исходного датафрейма.

In [16]:
import gc

In [17]:
who_ls

['drive', 'fines', 'gc', 'np', 'optimized', 'pd']

In [18]:
%reset_selective fines

Once deleted, variables cannot be recovered. Proceed (y/[n])?  n
Nothing done.

In [19]:
who_ls

['drive', 'fines', 'gc', 'np', 'optimized', 'pd']